# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 336)
        MainWindow.setMinimumSize(QtCore.QSize(80, 60))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(264, 230, 91, 23))
        self.export_button.setObjectName("export_button")
        self.file_location = QtWidgets.QPushButton(self.centralwidget)
        self.file_location.setGeometry(QtCore.QRect(264, 200, 91, 23))
        self.file_location.setObjectName("file_location")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 303, 151))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.url = QtWidgets.QLabel(self.widget)
        self.url.setStyleSheet("font: 16pt \"Calibri\";\n"
"background-color: rgb(255, 255, 255);")
        self.url.setObjectName("url")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.url)
        self.urlinput = QtWidgets.QTextEdit(self.widget)
        self.urlinput.setObjectName("urlinput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urlinput)
        self.export_location = QtWidgets.QLabel(self.widget)
        self.export_location.setStyleSheet("font: 16pt \"Calibri\";\n"
"background-color: rgb(255, 255, 255);")
        self.export_location.setObjectName("export_location")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.export_location)
        self.output = QtWidgets.QLabel(self.widget)
        self.output.setStyleSheet("font: 16pt \"Calibri\";")
        self.output.setObjectName("output")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.output)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.file_location.clicked.connect(self.choose_directory)
        #self.export_button.clicked.connect(self.export_to)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "โปรแกรมดึงข้อมูลหุ้น"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.file_location.setText(_translate("MainWindow", "Choose location"))
        self.url.setText(_translate("MainWindow", "URL:"))
        self.export_location.setText(_translate("MainWindow", "Export Location:"))
        self.output.setText(_translate("MainWindow", "file location"))
    
    def choose_directory(self):
        print("Hello")
        folderpath = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select Folder')
        self.output.setText(folderpath)
    
    def export_to(self):
        driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))

        url = self.urlinput.text()

        driver.get(url)

        data_list = pd.read_html(driver.page_source)
        data_list[0].to_excel(input_dir)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
